### ISSUE TITLE
Adding a Dataset for Characters Represented by Surrogate Pairs

### ISSUE THREAD

**Issue by ubugeeei** [asdfjkl/kanjicanvas#12]
# Adding a Dataset for Characters Represented by Surrogate Pairs

## Abstraction

Thank you for the wonderful tool. I really like this project. 😄 

When trying to add a dataset, I encountered some issues using jTegaki.

## Background Only One Character with a Single Code Point Can Be Registered

When setting the background, Unicode input is required, but characters represented by surrogate pairs are not considered.

Looking into the jTegaki source code decompiled with Java Decompiler, I found that it simply parses the hex of one block into a number and casts it to a char.

```java
int val_of_si = Integer.parseInt(s, 16);
char c_si = (char)val_of_si;
String si = Character.toString(c_si);
this.sp.setBackground(si);
this.sp.repaint();
```

## Request

Could jTegaki be improved to allow the addition of a dataset for characters represented by surrogate pairs?

```java
String input = "845B DB40 DD00"; // input from

String[] codePoints = input.split(" ");
StringBuilder result = new StringBuilder();

for (String codePoint : codePoints) {
    int cp = Integer.parseInt(codePoint, 16);
    result.append(Character.toChars(cp));
}
```

I considered making the improvement myself, but since the source code is not publicly available and the license is unclear, I decided to raise an issue.

**Comment by asdfjkl** [comment]
I've lost the source code to that jTegaki tool decades ago; have only the binary. It would probably make sense to recreate it in Python + Qt and automate the generation of javascript patterns, but due to limited time that's not on my list.

I have no overview how many kanji are affected, but I at least drawing and exporting should be still possible - it's just the background imagine that is missing.
